# Parameters used in the mpcc

# track parameters
track_name: "fssim_fsi"
track_optimization_length: 50.0

# car parameters
wheelbase: 1.5
wheel_radius: 0.2023 

# cost
ql: 1   # longitudinal cost
qc: 0.05 # lateral cost
ra: 0.00001  # acceleration cost
rs: 0.000000001  # steering cost
rz: 5   # zeta cost

# input boundary constraints
alpha_min: -15  # TODO: calculatet these!
alpha_max: 15 # 2*Tmax*GR/Rwheel/mass = 17.45m/s^2 (Tmax=140Nm, GR=3.405, Rwheel=0.2023m, mass=270kg)
phi_min: -1.5 # in 1 second from -45 to 45 degrees -> 60 degrees -> 1.571 rad/sec
phi_max: 1.5
zeta_min: 0.001
zeta_max: 1.2

# state boundary constraints
delta_min: -90 # maybe limit to 30 degrees?
delta_max: 90
v_min: 0
v_max: 12 #m/s
tau_min: 0.000000001
tau_max: 1

# nonlinear constraints
circle_radius: 0.8

# initial guess method
initial_guess: 'load' # 'calculate' or 'load' or 'load_and_shift'

multi_solve: true